services:
- type: web
  name: goodram-tender-intelligence
  runtime: docker
  plan: free
  healthCheckPath: /health
  envVars:
  - key: APP_LANGUAGE
    value: pl
  - key: BASE_API_TOKEN
    sync: false
